version: '3'
services:

  api:
    build: ./dataTheorem
    image: datatheorem:latest
    restart: always
    ports:
      - "8000:8000"
#    volumes:
#      - ./dataTheorem:/app

  web:
    build: ./www
    image: dtweb:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
